/* Quanta reference library — data. window.QRefData */
window.QRefData = (function () {
  // category tree: group -> [{id, label}]
  const TREE = {
    FUNCTIONS: [
      { id: 'mathtrig', label: 'Math & trig' },
      { id: 'stats', label: 'Statistics' },
      { id: 'solving', label: 'Solving' },
      { id: 'matrix', label: 'Matrix & vector' },
      { id: 'lookup', label: 'Lookup & data' },
      { id: 'programming', label: 'Programming' },
      { id: 'string', label: 'String' },
      { id: 'engineering', label: 'Engineering' },
    ],
    UNITS: [
      { id: 'length', label: 'Length' },
      { id: 'force', label: 'Force' },
      { id: 'pressure', label: 'Pressure / stress' },
      { id: 'mass', label: 'Mass' },
      { id: 'time', label: 'Time' },
      { id: 'temperature', label: 'Temperature' },
      { id: 'electrical', label: 'Electrical' },
    ],
    CONSTANTS: [
      { id: 'universal', label: 'Universal' },
      { id: 'electromagnetic', label: 'Electromagnetic' },
      { id: 'atomic', label: 'Atomic' },
    ],
  };

  // ---- functions ----
  const F = (o) => Object.assign({ kind: 'function' }, o);
  const FUNCTIONS = [
    F({ id: 'interp', cat: 'lookup', name: 'interp', sig: 'interp(vx, vy, x)', tag: 'Lookup & data',
      desc: 'Linear interpolation of a value x against paired data vectors.',
      params: [
        ['vx', 'vector', 'Strictly increasing x-data (e.g. heights).'],
        ['vy', 'vector', 'Matching y-data (e.g. pressures).'],
        ['x', 'real', 'Point to interpolate at; must lie within vx range.'],
      ],
      units: 'Result carries the units of vy. x must be unit-compatible with vx; mismatches flag inline.',
      related: ['linterp', 'Vlookup', 'cspline', 'lookup'],
      example: 'interp-wind' }),
    F({ id: 'vlookup', cat: 'lookup', name: 'Vlookup', sig: 'Vlookup(value, table, col, [match])', tag: 'Lookup & data',
      desc: 'Finds a value in the first column of a table and returns a cell from the same row.',
      params: [
        ['value', 'real | string', 'Value to search for in column 1.'],
        ['table', 'matrix', 'The lookup range.'],
        ['col', 'integer', 'Column index of the value to return.'],
        ['[match]', 'flag', 'Optional: 0 exact (default), 1 nearest-below.'],
      ],
      units: 'Returns the stored cell value with its units. The search value is compared dimensionally.',
      related: ['Hlookup', 'interp', 'lookup', 'match'],
      example: 'vlookup-bolt' }),
    F({ id: 'root', cat: 'solving', name: 'root', sig: 'root(f(x), x, [a, b])', tag: 'Solving',
      desc: 'Solves f(x) = 0 for x, optionally bracketed on [a, b].',
      params: [
        ['f(x)', 'expression', 'Function whose root is sought.'],
        ['x', 'variable', 'The unknown, with a guess value.'],
        ['[a, b]', 'real', 'Optional bracketing interval.'],
      ],
      units: 'x keeps the units of its guess; f is evaluated dimensionally at each step.',
      related: ['find', 'polyroots', 'minimize', 'Odesolve'],
      example: 'root-quad' }),
    F({ id: 'mean', cat: 'stats', name: 'mean', sig: 'mean(A)', tag: 'Statistics',
      desc: 'Arithmetic mean of the elements of a vector or matrix.',
      params: [['A', 'vector | matrix', 'Data to average.']],
      units: 'Result carries the common unit of the elements.',
      related: ['median', 'stdev', 'max', 'sum'],
      example: 'mean-loads' }),
    F({ id: 'max', cat: 'mathtrig', name: 'Max', sig: 'Max(a, b, …)', tag: 'Math & trig',
      desc: 'Returns the largest of its arguments or of a data set.',
      params: [['a, b, …', 'real | vector', 'Values or a data vector to compare.']],
      units: 'All arguments must share a dimension; the result keeps it.',
      related: ['Min', 'mean', 'sort', 'ceil'],
      example: 'max-util' }),
    F({ id: 'sqrt', cat: 'mathtrig', name: 'Sqrt', sig: 'Sqrt(x)', tag: 'Math & trig',
      desc: 'Principal square root of a non-negative real number.',
      params: [['x', 'real ≥ 0', 'The radicand.']],
      units: 'Returns the square-root of the argument units (e.g. mm² → mm).',
      related: ['cbrt', 'pow', 'exp', 'ln'],
      example: 'sqrt-area' }),
    F({ id: 'odesolve', cat: 'solving', name: 'Odesolve', sig: 'Odesolve(x, b, [steps])', tag: 'Solving',
      desc: 'Solves an ODE defined in a solve block over [0, b].',
      params: [
        ['x', 'variable', 'Independent variable.'],
        ['b', 'real', 'Upper limit of the solution interval.'],
        ['[steps]', 'integer', 'Optional number of integration steps.'],
      ],
      units: 'Solution and derivatives track the units declared in the solve block.',
      related: ['find', 'root', 'pdesolve', 'rkfixed'] }),
    F({ id: 'minimize', cat: 'solving', name: 'minimize', sig: 'minimize(f, x₀)', tag: 'Solving',
      desc: 'Finds the x that minimizes f, starting from guess x₀.',
      params: [['f', 'expression', 'Objective function.'], ['x₀', 'real | vector', 'Starting guess.']],
      units: 'x₀ sets the units of the optimisation variable.',
      related: ['maximize', 'root', 'find'] }),
    F({ id: 'linterp', cat: 'lookup', name: 'linterp', sig: 'linterp(vx, vy, x)', tag: 'Lookup & data',
      desc: 'Piecewise-linear interpolation that also extrapolates beyond the data.',
      params: [['vx', 'vector', 'x-data.'], ['vy', 'vector', 'y-data.'], ['x', 'real', 'Point to evaluate.']],
      units: 'Result carries the units of vy.',
      related: ['interp', 'cspline', 'Vlookup'] }),
    F({ id: 'stdev', cat: 'stats', name: 'stdev', sig: 'stdev(A)', tag: 'Statistics',
      desc: 'Population standard deviation of a data set.',
      params: [['A', 'vector | matrix', 'Data.']],
      units: 'Keeps the unit of the data.',
      related: ['Var', 'mean', 'median'] }),
    F({ id: 'identity', cat: 'matrix', name: 'identity', sig: 'identity(n)', tag: 'Matrix & vector',
      desc: 'Returns the n × n identity matrix.',
      params: [['n', 'integer', 'Matrix order.']],
      units: 'Dimensionless.',
      related: ['diag', 'transpose', 'inverse'] }),
    F({ id: 'transpose', cat: 'matrix', name: 'transpose', sig: 'transpose(M)', tag: 'Matrix & vector',
      desc: 'Swaps the rows and columns of a matrix.',
      params: [['M', 'matrix', 'Input matrix.']],
      units: 'Element units are preserved.',
      related: ['identity', 'inverse', 'det'] }),
    F({ id: 'if', cat: 'programming', name: 'if', sig: 'if(cond, then, else)', tag: 'Programming',
      desc: 'Returns then when cond is true, otherwise else.',
      params: [['cond', 'boolean', 'Condition to test.'], ['then', 'any', 'Value if true.'], ['else', 'any', 'Value if false.']],
      units: 'then and else should share a dimension.',
      related: ['until', 'and', 'or'] }),
    F({ id: 'concat', cat: 'string', name: 'concat', sig: 'concat(s1, s2, …)', tag: 'String',
      desc: 'Joins two or more strings into one.',
      params: [['s1, s2, …', 'string', 'Strings to join.']],
      units: 'Not applicable.',
      related: ['substr', 'strlen', 'num2str'] }),
    F({ id: 'reynolds', cat: 'engineering', name: 'Re', sig: 'Re(ρ, v, L, μ)', tag: 'Engineering',
      desc: 'Reynolds number for flow characterisation.',
      params: [['ρ', 'density', 'Fluid density.'], ['v', 'velocity', 'Flow velocity.'], ['L', 'length', 'Characteristic length.'], ['μ', 'viscosity', 'Dynamic viscosity.']],
      units: 'Dimensionless result; arguments are checked for consistency.',
      related: ['Nu', 'Pr', 'froude'] }),
  ];

  // ---- units ----
  const U = (o) => Object.assign({ kind: 'unit' }, o);
  const UNITS = [
    U({ id: 'mm', cat: 'length', name: 'mm', sig: 'millimetre', tag: 'Length', desc: 'SI length, 10⁻³ m.', base: '0.001 m', dim: 'L', related: ['m', 'cm', 'in'] }),
    U({ id: 'm', cat: 'length', name: 'm', sig: 'metre', tag: 'Length', desc: 'SI base unit of length.', base: '1 m', dim: 'L', related: ['mm', 'km', 'ft'] }),
    U({ id: 'in', cat: 'length', name: 'in', sig: 'inch', tag: 'Length', desc: 'USCS length.', base: '0.0254 m', dim: 'L', related: ['ft', 'mm'] }),
    U({ id: 'kN', cat: 'force', name: 'kN', sig: 'kilonewton', tag: 'Force', desc: 'SI force, 10³ N.', base: '1000 N', dim: 'M·L·T⁻²', related: ['N', 'MN', 'kip'] }),
    U({ id: 'N', cat: 'force', name: 'N', sig: 'newton', tag: 'Force', desc: 'SI derived unit of force.', base: '1 kg·m/s²', dim: 'M·L·T⁻²', related: ['kN', 'lbf'] }),
    U({ id: 'kip', cat: 'force', name: 'kip', sig: 'kilopound-force', tag: 'Force', desc: 'USCS force, 1000 lbf.', base: '4448.22 N', dim: 'M·L·T⁻²', related: ['lbf', 'kN'] }),
    U({ id: 'MPa', cat: 'pressure', name: 'MPa', sig: 'megapascal', tag: 'Pressure / stress', desc: 'SI stress, 10⁶ Pa = N/mm².', base: '1e6 Pa', dim: 'M·L⁻¹·T⁻²', related: ['Pa', 'kPa', 'ksi'] }),
    U({ id: 'kPa', cat: 'pressure', name: 'kPa', sig: 'kilopascal', tag: 'Pressure / stress', desc: 'SI pressure, 10³ Pa.', base: '1000 Pa', dim: 'M·L⁻¹·T⁻²', related: ['Pa', 'MPa', 'psf'] }),
    U({ id: 'ksi', cat: 'pressure', name: 'ksi', sig: 'kips per sq. inch', tag: 'Pressure / stress', desc: 'USCS stress.', base: '6.895e6 Pa', dim: 'M·L⁻¹·T⁻²', related: ['psi', 'MPa'] }),
    U({ id: 'kg', cat: 'mass', name: 'kg', sig: 'kilogram', tag: 'Mass', desc: 'SI base unit of mass.', base: '1 kg', dim: 'M', related: ['g', 't', 'lb'] }),
    U({ id: 's', cat: 'time', name: 's', sig: 'second', tag: 'Time', desc: 'SI base unit of time.', base: '1 s', dim: 'T', related: ['ms', 'min', 'hr'] }),
    U({ id: 'degC', cat: 'temperature', name: '°C', sig: 'degree Celsius', tag: 'Temperature', desc: 'Common temperature scale; affine to K.', base: 'K − 273.15', dim: 'Θ', related: ['K', '°F'] }),
    U({ id: 'A', cat: 'electrical', name: 'A', sig: 'ampere', tag: 'Electrical', desc: 'SI base unit of electric current.', base: '1 A', dim: 'I', related: ['mA', 'V', 'Ω'] }),
  ];

  // ---- constants ----
  const C = (o) => Object.assign({ kind: 'constant' }, o);
  const CONSTANTS = [
    C({ id: 'g0', cat: 'universal', name: 'g₀', sig: 'standard gravity', tag: 'Universal', desc: 'Standard acceleration due to gravity.', value: '9.80665', unit: 'm/s²', source: 'CODATA (defined)', related: ['G', 'c'] }),
    C({ id: 'G', cat: 'universal', name: 'G', sig: 'gravitational constant', tag: 'Universal', desc: 'Newtonian constant of gravitation.', value: '6.67430 × 10⁻¹¹', unit: 'm³·kg⁻¹·s⁻²', source: 'CODATA 2018', related: ['g₀'] }),
    C({ id: 'c', cat: 'universal', name: 'c', sig: 'speed of light', tag: 'Universal', desc: 'Speed of light in vacuum.', value: '2.99792458 × 10⁸', unit: 'm/s', source: 'SI (defined)', related: ['h', 'ε₀'] }),
    C({ id: 'NA', cat: 'atomic', name: 'Nₐ', sig: 'Avogadro constant', tag: 'Atomic', desc: 'Number of entities per mole.', value: '6.02214076 × 10²³', unit: 'mol⁻¹', source: 'SI (defined)', related: ['k', 'R'] }),
    C({ id: 'k', cat: 'atomic', name: 'k', sig: 'Boltzmann constant', tag: 'Atomic', desc: 'Relates temperature to energy.', value: '1.380649 × 10⁻²³', unit: 'J/K', source: 'SI (defined)', related: ['Nₐ', 'R'] }),
    C({ id: 'e', cat: 'electromagnetic', name: 'e', sig: 'elementary charge', tag: 'Electromagnetic', desc: 'Electric charge of a proton.', value: '1.602176634 × 10⁻¹⁹', unit: 'C', source: 'SI (defined)', related: ['ε₀', 'μ₀'] }),
    C({ id: 'eps0', cat: 'electromagnetic', name: 'ε₀', sig: 'vacuum permittivity', tag: 'Electromagnetic', desc: 'Electric constant of free space.', value: '8.8541878128 × 10⁻¹²', unit: 'F/m', source: 'CODATA 2018', related: ['μ₀', 'c'] }),
  ];

  const ALL = [...FUNCTIONS, ...UNITS, ...CONSTANTS];
  return { TREE, FUNCTIONS, UNITS, CONSTANTS, ALL };
})();
